[package]
name = "del-gl"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.29.1"
del-misc = "0.1.0"

[build-dependencies]
gl_generator = "0.14.0"